//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRZPayment
    {
        public long PaymentID { get; set; }
        public string BookingNo { get; set; }
        public decimal Amount { get; set; }
        public decimal Tax { get; set; }
        public decimal TotalAmount { get; set; }
        public string RoomId { get; set; }
        public int TelephoneNo { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string RoomNo { get; set; }
        public string CreditCardNo { get; set; }
    }
}
