//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageRep
    {
        public long ImageRepID { get; set; }
        public int HotelCode { get; set; }
        public string imageTypeCode { get; set; }
        public string hotel { get; set; }
        public string path { get; set; }
        public string roomCode { get; set; }
        public string roomType { get; set; }
        public string characteristicCode { get; set; }
        public int order { get; set; }
    }
}
