//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRep
    {
        public long HotelRepID { get; set; }
        public int code { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string countryCode { get; set; }
        public string destinationCode { get; set; }
        public short zoneCode { get; set; }
        public string categoryCode { get; set; }
        public string categoryGroupCode { get; set; }
        public string chainCode { get; set; }
        public string accommodationTypeCode { get; set; }
        public string address { get; set; }
        public string postalCode { get; set; }
        public string city { get; set; }
        public string email { get; set; }
        public string license { get; set; }
        public int giataCode { get; set; }
        public int hotelstar { get; set; }
        public string imagepath { get; set; }
        public string destinationName { get; set; }
        public string categoryName { get; set; }
        public string hotel_board_basis { get; set; }
        public string phoneNumber { get; set; }
    }
}
