//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentMarkup
    {
        public string UserID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Presentage { get; set; }
        public long AgentMarkupID { get; set; }
        public string Email { get; set; }
        public string password { get; set; }
    }
}
