//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyRate
    {
        public string Currency { get; set; }
        public Nullable<decimal> Value { get; set; }
        public long CurrencyRateID { get; set; }
    }
}
