//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityTypeRep
    {
        public long FacilityTypeRepID { get; set; }
        public int code { get; set; }
        public bool conceptFlag { get; set; }
        public bool numberFlag { get; set; }
        public bool logicFlag { get; set; }
        public bool feeFlag { get; set; }
        public bool distanceFlag { get; set; }
        public bool ageFromFlag { get; set; }
        public bool ageToFlag { get; set; }
        public bool dateFromFlag { get; set; }
        public bool dateToFlag { get; set; }
        public bool timeFromFlag { get; set; }
        public bool timeToFlag { get; set; }
        public bool indYesOrNoFlag { get; set; }
        public bool amountFlag { get; set; }
        public bool currencyFlag { get; set; }
        public bool appTypeFlag { get; set; }
    }
}
