//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRZHotelSupplier
    {
        public long HotelSupplierID { get; set; }
        public string HotelCode { get; set; }
        public string Address { get; set; }
        public string HotelName { get; set; }
        public string StarRating { get; set; }
        public string ContactPerson { get; set; }
        public string Owner { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string Description { get; set; }
        public string IsInternetAvailable { get; set; }
        public string TypeOfInternet { get; set; }
        public string WhereIsInternet { get; set; }
        public string IsParkingAvailable { get; set; }
        public string ParkingPrivateOrOnSite { get; set; }
        public string ReservationNeedForParking { get; set; }
        public string PriceForParking { get; set; }
        public string AccomodateChildren { get; set; }
        public string PetsAllowed { get; set; }
        public string SpeakingLanguage { get; set; }
        public string CheckInTime { get; set; }
        public string CheckOutTime { get; set; }
        public string IsLocal { get; set; }
    }
}
