//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalRep
    {
        public long TerminalRepID { get; set; }
        public string code { get; set; }
        public string type { get; set; }
        public string country { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    }
}
