//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryRep
    {
        public long CategoryRepID { get; set; }
        public string code { get; set; }
        public int simpleCode { get; set; }
        public string accommodationType { get; set; }
        public string group { get; set; }
        public string description { get; set; }
    }
}
