//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelBoardCodesRep
    {
        public long HotelBoardCodesRepID { get; set; }
        public int HotelCode { get; set; }
        public int code { get; set; }
        public string BoardCode { get; set; }
    }
}
