//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelPaymentDetail
    {
        public string clientID { get; set; }
        public string currency { get; set; }
        public string holderName { get; set; }
        public string number { get; set; }
        public decimal paymentAmount { get; set; }
        public string responseCode { get; set; }
        public string responseText { get; set; }
        public string txnReference { get; set; }
        public string type { get; set; }
    }
}
