//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoLocationRep
    {
        public long GeoLocationRepID { get; set; }
        public int HotelCode { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<decimal> radius { get; set; }
        public Nullable<int> unit { get; set; }
        public double secondaryLatitude { get; set; }
        public double secondaryLongitude { get; set; }
    }
}
