//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRZUserPrivilege
    {
        public Nullable<long> HRZUserPrivilegesID { get; set; }
        public int UserType { get; set; }
        public long FormID { get; set; }
        public long IsAccess { get; set; }
        public long IsDelete { get; set; }
    }
}
