//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueRep
    {
        public long IssueRepID { get; set; }
        public string code { get; set; }
        public string type { get; set; }
        public string description { get; set; }
        public string name { get; set; }
        public bool alternative { get; set; }
    }
}
