//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateCommentRep
    {
        public long RateCommentRepID { get; set; }
        public int HotelCode { get; set; }
        public System.DateTime dateEnd { get; set; }
        public System.DateTime dateStart { get; set; }
        public string description { get; set; }
    }
}
